
import "./globals.css";
import { Inter, DM_Sans, Manrope } from '@next/font/google';

const inter = Inter({
  weight: '400',
  subsets: ['latin'],
});

const dmSans = DM_Sans({
  weight: '700',
  subsets: ['latin'],
});

const manrope = Manrope({
  weight: '400',
  subsets: ['latin'],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        {children}
      </body>
    </html>
  );
}
